---
- name: Pre-tasks (updates)
  hosts: all
  become: true
  pre_tasks:

    - name: Install updates for Fedora (dnf5-safe)
      tags: always
      ansible.builtin.command: dnf5 -y upgrade --refresh --security --bugfix
      when: ansible_distribution == "Fedora"

    - name: Install updates for Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"


- name: Apply base role to all hosts
  hosts: all
  become: true
  roles:
    - base


- name: Apply db role to db servers
  hosts: db_servers
  become: true
  roles:
    - db_servers


- name: Apply web role to web servers
  hosts: web_servers
  become: true
  roles:
    - web_servers
